### ISSUE TITLE
harmony-0.1.0.0 doesn't compile

### ISSUE THREAD

**Issue by peti** [SantiMunin/harmony#80]
A complete build log is at http://hydra.cryp.to/build/1064638/log/raw.

**Comment by SantiMunin** [comment]
Thanks Peter, looking into that.

**Comment by SantiMunin** [comment]
Can you try now please?

**Comment by peti** [comment]
The current git HEAD builds fine. Thank you very much for the fix!

**Comment by SantiMunin** [comment]
No problem, thank you for noticing!
